### ISSUE TITLE
The performance w/o overlapping patches and additional data transformation[RandomGrayscalePatchReplacement(probability=cfg.INPUT.GS_PROB),]?

### ISSUE THREAD

**Issue by 924973292** [Nano1337/UniCat#1]
Nice work!
I wonder the performance of UniCat with the stride of [16,16] and w/o the additional "RandomGrayscalePatchReplacement"(compared to TransReID), could you release the result?
Thanks a lot!

**Comment by crawfj10** [comment]
Hi, thanks for your interest in Unicat! To be clear, our original UniCat implementation for ViT doesn't use TransReID's JPM module or SIE embeddings, but is ViT with stride=12. I ran UniCat 1) without the random grayscale augmentation and 2) with stride 16 as opposed to the original 12. The results are as follows for a single random seed:

RGBNT100: 

No grayscale and stride=12: mAP = 81.8, Rank-1 = 97.7 
No grayscale and stride=16: mAP = 79.4, Rank-1 = 96.2


RGBN300:

No grayscale and stride=12: mAP = 80.5, Rank-1 = 94.2
No grayscale and stride=16: mAP = 79.6, Rank-1  = 92.5


RGBNT201:

No grayscale and stride=12: mAP = 60.9, Rank-1  = 58.7
No grayscale and stride=16: mAP = 57.0, Rank-1  = 55.7


It's clear that having stride=12 gives the ViT greater representational power. However, removing the random grayscale augmentation doesn't harm performance as compared to the results in our paper. In fact, removing it may further boost performance (more random seeds would need to be run to confirm).

**Comment by 924973292** [comment]
Thank you for your thoughtful and detailed response!
